In [4]:
import pandas as pd
import numpy as np

df = pd.read_csv("../data/raw/synthetic_user_data.csv")

In [5]:
X = df.drop(columns=['user_id', 'fraud_risk', 'churn_risk'])

In [6]:
y = df[['fraud_risk', 'churn_risk']]

In [7]:
X = pd.get_dummies(X, columns=['payment_method'], drop_first=True)

In [9]:
X.head()

,transaction_amount,transaction_hour,transaction_frequency,unusual_location,account_age_days,login_frequency,support_contacts,notifications_opted_out,payment_method_credit_card,payment_method_mobile_payment
0,254.838419,7,8,0,584,26,1,0,False,False
1,1998.104433,1,19,1,175,13,1,0,False,False
2,285.706723,16,9,0,2939,9,6,1,False,False
3,50.818266,18,7,0,1173,32,1,0,True,False
4,100.934316,20,9,0,3555,4,5,1,False,True

In [10]:
X = X.astype({col: int for col in X.columns if X[col].dtype == bool})

In [11]:
X.head()

,transaction_amount,transaction_hour,transaction_frequency,unusual_location,account_age_days,login_frequency,support_contacts,notifications_opted_out,payment_method_credit_card,payment_method_mobile_payment
0,254.838419,7,8,0,584,26,1,0,0,0
1,1998.104433,1,19,1,175,13,1,0,0,0
2,285.706723,16,9,0,2939,9,6,1,0,0
3,50.818266,18,7,0,1173,32,1,0,1,0
4,100.934316,20,9,0,3555,4,5,1,0,1

In [12]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

cols_to_scale = ['transaction_amount', 'transaction_hour', 
                 'transaction_frequency', 'account_age_days',
                 'login_frequency', 'support_contacts']

X[cols_to_scale] = scaler.fit_transform(X[cols_to_scale])