In [2]:
import pandas as pd
import numpy as np
import joblib
df = pd.read_csv("../data/raw/synthetic_user_data.csv")

In [3]:
X = df.drop(columns=['user_id', 'fraud_risk', 'churn_risk'])

In [4]:
y = df[['fraud_risk', 'churn_risk']]

In [5]:
X = pd.get_dummies(X, columns=['payment_method'], drop_first=True)

In [6]:
X.head()

,transaction_amount,transaction_hour,transaction_frequency,unusual_location,account_age_days,login_frequency,support_contacts,notifications_opted_out,payment_method_credit_card,payment_method_mobile_payment
0,3671.804098,3,36,0,584,6,6,0,False,False
1,1998.104433,1,19,1,175,13,1,0,False,False
2,285.706723,16,9,0,2939,9,6,1,False,False
3,50.818266,18,7,0,1173,32,1,0,True,False
4,100.934316,20,9,0,3555,4,5,1,False,True

In [7]:
X = X.astype({col: int for col in X.columns if X[col].dtype == bool})

In [8]:
X.head()

,transaction_amount,transaction_hour,transaction_frequency,unusual_location,account_age_days,login_frequency,support_contacts,notifications_opted_out,payment_method_credit_card,payment_method_mobile_payment
0,3671.804098,3,36,0,584,6,6,0,0,0
1,1998.104433,1,19,1,175,13,1,0,0,0
2,285.706723,16,9,0,2939,9,6,1,0,0
3,50.818266,18,7,0,1173,32,1,0,1,0
4,100.934316,20,9,0,3555,4,5,1,0,1

In [9]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [10]:
X_train = X_train.reset_index(drop=True)
X_test = X_test.reset_index(drop=True)
y_train = y_train.reset_index(drop=True)
y_test = y_test.reset_index(drop=True)

In [11]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

cols_to_scale = ['transaction_amount', 'transaction_hour', 
                 'transaction_frequency', 'account_age_days',
                 'login_frequency', 'support_contacts']

X_train[cols_to_scale] = scaler.fit_transform(X_train[cols_to_scale])
X_test[cols_to_scale] = scaler.transform(X_test[cols_to_scale])

In [12]:
joblib.dump(scaler, '../models/scaler.joblib')

['../models/scaler.joblib']

In [13]:
X[['transaction_amount', 'account_age_days', 'login_frequency']].describe()

       transaction_amount  account_age_days  login_frequency
count         5000.000000       5000.000000      5000.000000
mean           718.589745       1816.480400        22.448400
std           1117.529241       1048.620547        14.885767
min             10.123703          1.000000         1.000000
25%            167.062602        920.500000         8.000000
50%            316.583922       1802.500000        21.000000
75%            463.190287       2703.250000        35.000000
max           4979.971691       3649.000000        49.000000

In [14]:
X_train.to_csv("../data/processed/X_train.csv", index=False)
X_test.to_csv("../data/processed/X_test.csv", index=False)
y_train.to_csv("../data/processed/y_train.csv", index=False)
y_test.to_csv("../data/processed/y_test.csv", index=False)